### ISSUE TITLE
Seed words are in German

### ISSUE THREAD

**Issue by ra-dave** [XzenTorXz/ElectroneumGUIWallet#1]
Is there any way to get English seed words?

**Comment by cirim-au** [comment]
Issue with /settings/__init__.py with order or referencing of languages for seeds. Use German and you should get English for now.

Seed language list needs updating or fixing.

**Comment by XzenTorXz** [comment]
The seeds where not workink, so I didnt bother with the language.

The seeds are now working. Also the language mapping is fixed. thanks for the hint @kiintorg 

The source is updated and the release is uploading.
