### ISSUE TITLE
Could I move data.mdb to other folder?

### ISSUE THREAD

**Issue by flier268** [XzenTorXz/ElectroneumGUIWallet#10]
Could I move data.mdb to other folder?
It is because my C: is SSD,and it did't have large space

**Comment by XzenTorXz** [comment]
it sounds like you're on windows:
- move your C:\path\To\Wallet\data to your d drive like D:\newWalletData
- open your terminal and create a shortcut with "mklink /J C:\path\To\Wallet\data D:\newDataWallet"

**Comment by flier268** [comment]
Sucess
Thank you.
