### ISSUE TITLE
Loading walet.... takes forever

### ISSUE THREAD

**Issue by Sapegu** [XzenTorXz/ElectroneumGUIWallet#11]
Hi,

I loaded my wallet into the GUI, and it synchronized but then it satays forever in a window saying Loading Wallet...
![electroneum](https://user-images.githubusercontent.com/36778893/36945959-5bac9182-1fad-11e8-9afd-1be9ebb3f2e5.jpg)

**Comment by XzenTorXz** [comment]
yes this is a common issue with sumokoin wallet, since it has to scans the whole blockchain and doesn't provide any visual feedback. I might integrate a blockheight to display.

**Comment by Sapegu** [comment]
Does that mean tat it is working? Should i leave it working?

**Comment by XzenTorXz** [comment]
it should be working, but it needs to scan the whole blockchain that can take a long time.

**Comment by XzenTorXz** [comment]
i just created an update, that adds some visual feedback after a while.
