### ISSUE TITLE
No funds since 08/03/2018

### ISSUE THREAD

**Issue by syrius01** [XzenTorXz/ElectroneumGUIWallet#13]
Hi,

Not sure if you can help.. I got multiple transactions from 2 pools to my wallet and I don't see/receive any of them on my wallet since 08/03/2018.

Any help would be very appreciated.

Thanks.

**Comment by saginardo** [comment]
Since last time there was a bug in Electroneum blockchain which cause the block stuck on 179848 height, maybe you should update your binaries or just download the newest release.

**Comment by syrius01** [comment]
Would it be possible to tell me how to update the binaries and keep the same wallet address in order to not loose the 5 transactions funds that I've not received since the 08/03/2018?

Thank you for your time.

**Comment by saginardo** [comment]
you can download binaries from https://github.com/electroneum/electroneum/releases, unzip and replace all files to the Resources\bin.

**Comment by syrius01** [comment]
I don't have a resources\bin folder. I copy/pasted all the files to the main folder and replaced the files with the same name with the new files which corrupted the wallet and cannot open it. Luckily, I have made a backup before replacing all the files so I can still open the old wallet. 

I have a pending transaction right now (receiving funds from a pool) which is unconfirmed. We'll see if it's confirmed later on... About the 5 last days (3900 ETN), are those funds lost or there could be a way to recover them?

**Comment by syrius01** [comment]
update: the unconfirmed balance just disappeared :( i'm contacting electroneum support to see if they can do something on their side.

**Comment by saginardo** [comment]
![image](https://user-images.githubusercontent.com/9972713/37436917-59fec5dc-2825-11e8-87ca-94c1b9ed52a4.png)
this is the folder which you should replace all electroneum binaries.
Another way, you may write down your mnemonic seed(in settings), download a new ElectroneumGUIWallet release, and chose to restore your wallet from this seed.

**Comment by syrius01** [comment]
![image](https://user-images.githubusercontent.com/20993648/37439409-5db9fec8-27ce-11e8-8d91-b06943f2e549.png)

 As you can see on the image above, there is no 'Resources' folder.

![image](https://user-images.githubusercontent.com/20993648/37439447-90102b90-27ce-11e8-9451-9597e4a1731e.png)

On the second picture you can see the content of the main folder. about the option B (mnemonic seed in settings), could you give me the more details as possible to to this ?

Thank you again, your help is very appreciated.

**Comment by saginardo** [comment]
![image](https://user-images.githubusercontent.com/9972713/37439590-ba6c4ec2-2833-11e8-974f-67a2f9da09aa.png)
click this button, and enter your password, you can see your mnemonic seed.

Warning, here is a example, don't post any of your mnemonic seed.
![image](https://user-images.githubusercontent.com/9972713/37439653-00726ea6-2834-11e8-8400-a0a6c16a06be.png)

You just need to download ElectroneumGUIWallet latest release, unzip it to somewhere and restore your wallet.
Remember that anyone own this mnemonic seed can restore wallet without any password.
![image](https://user-images.githubusercontent.com/9972713/37439688-2cf1df3e-2834-11e8-914a-bdd658a6eb24.png)

**Comment by XzenTorXz** [comment]
@saginardo thanks for you help
@syrius01 this is not my gui wallet, this looks like a "monereo wallet fork", you should take a look where you downloaded the wallet or you might find the repo in a readme file and create a issue there

**Comment by syrius01** [comment]
OK I will use your latest release wallet with my mnemonic seed. Will keep you updated on how it goes.

Great support btw, i'm very happy with your help :)

**Comment by syrius01** [comment]
Good news! after recovering the wallet with my mnemonic seed with your latest release, I have all my funds and wallet is well sync.

Thanks for your help !

You can close this ticket

**Comment by XzenTorXz** [comment]
good to hear ;-)
