### ISSUE TITLE
Daemon Error

### ISSUE THREAD

**Issue by ghost** [XzenTorXz/ElectroneumGUIWallet#7]
I get this when I try to send coins to exchange:
error sending coins
Error 
transaction was rejected by daemon

I tried reducing the amount, same thing happens.
address & pay ID are correct

**Comment by XzenTorXz** [comment]
this is mostly the case when there is not enough coins left for the transaction fees. I implemented a method to send all coins for this specific case (just enter the entire amount of coins).
