### ISSUE TITLE
Walled spend-key ERROR

### ISSUE THREAD

**Issue by funymanoo** [XzenTorXz/ElectroneumGUIWallet#8]
Hello! 
I need Spend-Key.   Settings ---> spendkey ----> Error(((( 
Help Me! 
Ths

**Comment by XzenTorXz** [comment]
https://github.com/XzenTorXz/ElectroneumGUIWallet/issues/3 duplicate

**Comment by XzenTorXz** [comment]
you can still open the wallet-cli manually and type in spendkey, to see your spendkey. At the moment I still waiting for electroneum to release a new version of their wallet-rpc
